# Generated by Django 6.0 on 2026-02-04 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shopapp', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
    ]
