# Generated by Django 6.0 on 2026-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0008_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(null=True, upload_to="orders/receipts/"),
        ),
    ]
