# Generated by Django 6.0 on 2026-04-26 20:21

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0009_order_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
            ),
        ),
    ]
